/**
 * Created by MoonJR on 2016. 1. 11..
 */

const FLAG_ERROR_CODE = 1000;
const FLAG_SUCCESS_CODE = 2000;
const FLAG_LOGIN_FAIL_CODE = 3000;
const FLAG_FACEBOOK_LOGIN_FAIL_CODE = 3001;
const FLAG_SESSION_FAIL_CODE = 3002;
const FLAG_SIGNUP_EXIST_EMAIL_CODE = 4000;
const FLAG_OVER_UPLOAD_MAX_SIZE_CODE = 5000;
const FLAG_FILE_NOT_FOUND_CODE = 6000;
const FLAG_FILE_DOWNLOAD_OVER_CODE = 6001;
const FLAG_FILE_DEADLINE_CODE = 6002;
const FLAG_FILE_NOT_FOUND_CODE_CODE = 6003;
const FLAG_FILE_FAIL_PASSWD_CODE = 6004;
const FLAG_FILE_REQUIRE_PASSWD_CODE = 6005;


const FLAG_ERROR_MESSAGE = "에러 발생";
const FLAG_SUCCESS_MESSAGE = "성공";
const FLAG_LOGIN_FAIL_MESSAGE = "회원정보 불일치";
const FLAG_FACEBOOK_LOGIN_FAIL_MESSAGE = "계정 정보 가져오기 실패";
const FLAG_SESSION_FAIL_MESSAGE = "로그인후 이용해 주세요.";
const FLAG_SIGNUP_EXIST_EMAIL_MESSAGE = "이미 회원입니다.";
const FLAG_OVER_UPLOAD_MAX_SIZE_MESSAGE = "업로드 가능 용량 초과";
const FLAG_FILE_NOT_FOUND_MESSAGE = "파일을 찾을 수 없습니다.";
const FLAG_FILE_DOWNLOAD_OVER_MESSAGE = "파일 다운로드 횟수를 초과하였습니다.";
const FLAG_FILE_DEADLINE_MESSAGE = "파일 기간이 만료 되었습니다.";
const FLAG_FILE_NOT_FOUND_CODE_MESSAGE = '해당 코드를 찾을수 없습니다.';
const FLAG_FILE_FAIL_PASSWD_MESSAGE = '비밀번호가 틀렸습니다.';
const FLAG_FILE_REQUIRE_PASSWD_MESSAGE = '비밀번호가 필요합니다.';


const FLAG_ERROR_JSON = {
    success_code: FLAG_ERROR_CODE,
    success_msg: FLAG_ERROR_MESSAGE
};

const FLAG_SUCCESS_JSON = {
    success_code: FLAG_SUCCESS_CODE,
    success_msg: FLAG_SUCCESS_MESSAGE
};
const FLAG_LOGIN_FAIL_JSON = {
    success_code: FLAG_LOGIN_FAIL_CODE,
    success_msg: FLAG_LOGIN_FAIL_MESSAGE
};
const FLAG_FACEBOOK_LOGIN_FAIL_JSON = {
    success_code: FLAG_FACEBOOK_LOGIN_FAIL_CODE,
    success_msg: FLAG_FACEBOOK_LOGIN_FAIL_MESSAGE
};
const FLAG_SESSION_FAIL_JSON = {
    success_code: FLAG_SESSION_FAIL_CODE,
    success_msg: FLAG_SESSION_FAIL_MESSAGE
};
const FLAG_SIGNUP_EXIST_EMAIL = {
    success_code: FLAG_SIGNUP_EXIST_EMAIL_CODE,
    success_msg: FLAG_SIGNUP_EXIST_EMAIL_MESSAGE
};
const FLAG_OVER_UPLOAD_MAX_SIZE_JSON = {
    success_code: FLAG_OVER_UPLOAD_MAX_SIZE_CODE,
    success_msg: FLAG_OVER_UPLOAD_MAX_SIZE_MESSAGE
};
const FLAG_FILE_NOT_FOUND_JSON = {
    success_code: FLAG_FILE_NOT_FOUND_CODE,
    success_msg: FLAG_FILE_NOT_FOUND_MESSAGE
};
const FLAG_FILE_DOWNLOAD_OVER_JSON = {
    success_code: FLAG_FILE_DOWNLOAD_OVER_CODE,
    success_msg: FLAG_FILE_DOWNLOAD_OVER_MESSAGE
};
const FLAG_FILE_DEADLINE_JSON = {
    success_code: FLAG_FILE_DEADLINE_CODE,
    success_msg: FLAG_FILE_DEADLINE_MESSAGE
};
const FLAG_FILE_NOT_FOUND_CODE_JSON = {
    success_code: FLAG_FILE_NOT_FOUND_CODE_CODE,
    success_msg: FLAG_FILE_NOT_FOUND_CODE_MESSAGE
};
const FLAG_FILE_FAIL_PASSWD_JSON = {
    success_code: FLAG_FILE_FAIL_PASSWD_CODE,
    success_msg: FLAG_FILE_FAIL_PASSWD_MESSAGE
};

const FLAG_FILE_REQUIRE_PASSWD_JSON = {
    success_code: FLAG_FILE_REQUIRE_PASSWD_CODE,
    success_msg: FLAG_FILE_REQUIRE_PASSWD_MESSAGE
};


exports.FLAG_ERROR_JSON = FLAG_ERROR_JSON;
exports.FLAG_SUCCESS_JSON = FLAG_SUCCESS_JSON;
exports.FLAG_LOGIN_FAIL_JSON = FLAG_LOGIN_FAIL_JSON;
exports.FLAG_FACEBOOK_LOGIN_FAIL_JSON = FLAG_FACEBOOK_LOGIN_FAIL_JSON;
exports.FLAG_SESSION_FAIL_JSON = FLAG_SESSION_FAIL_JSON;
exports.FLAG_SIGNUP_EXIST_EMAIL = FLAG_SIGNUP_EXIST_EMAIL;
exports.FLAG_OVER_UPLOAD_MAX_SIZE_JSON = FLAG_OVER_UPLOAD_MAX_SIZE_JSON;
exports.FLAG_FILE_NOT_FOUND_JSON = FLAG_FILE_NOT_FOUND_JSON;
exports.FLAG_FILE_DOWNLOAD_OVER_JSON = FLAG_FILE_DOWNLOAD_OVER_JSON;
exports.FLAG_FILE_DEADLINE_JSON = FLAG_FILE_DEADLINE_JSON;
exports.FLAG_FILE_NOT_FOUND_CODE_JSON = FLAG_FILE_NOT_FOUND_CODE_JSON;
exports.FLAG_FILE_FAIL_PASSWD_JSON = FLAG_FILE_FAIL_PASSWD_JSON;
exports.FLAG_FILE_REQUIRE_PASSWD_JSON = FLAG_FILE_REQUIRE_PASSWD_JSON;

exports.FLAG_CONTENTS_TYPE_STRING = 1;
exports.FLAG_CONTENTS_TYPE_FILE = 2;
